name: wechat_camera_picker
description: A camera picker based on WeChat's UI which is a separate runnable extension to wechat_assets_picker.
repository: https://github.com/fluttercandies/flutter_wechat_camera_picker
version: 3.8.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  camera: 0.10.5+2
  camera_platform_interface: 2.5.0
  path: 1.8.2
  photo_manager: 2.4.0
  video_player: 2.4.5
